# Generated by Django 5.0.6 on 2024-06-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(unique=True)),
                ('skills', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
