# Generated by Django 5.0.6 on 2024-06-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_workexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(unique=True)),
                ('skills', models.TextField(blank=True)),
                ('repository', models.URLField(blank=True)),
                ('image', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
